dist: bionic
language: scala
scala:
- 2.13.5
env:
  jobs:
  - JDK=openjdk8
  global:
  - GPG_TTY=$(tty)
  - secure: auXFjDs/6Ks2hcE6+aPfybJz8kgRue8OeLvD3BXQ+5J78RGtksohw4pfXq3a/mR1xcGccLhTJBiFzRhb32+2lJXHMyFanCubaQC9hB/khzZn6iqZh+orhR5taK77M1fwxYElhImMIN3PYwM8jq1dEdRk3x8a/a70FQou1ceLFILJTJ5DVDpIuQZNGAg53KZWizCH/qqSbGyu0cSvOXz1KWUR96o7t7Sv7JXr0lmixLeQMXXgEW9MQpE5iOfCaS8ECojrvZaUt7Lhrpj/7caFMA/bioVGjPJOQF9EgZV8ScdVXjEGN335j4LyMdYylACyvBKF8YVxINd+wxEBQEg//KQWJt3PTdKNZ5NeyzEimqI5ssfnqh+uOG45N22T/Bkixn9WDzexfkBgGMrQTd0nc4rbWnqzznKkVkIW/YoMj6YE11XMHfy4xRvtABIVwWVZVohCqyY30C0G7gyoxbbO3WqJYEFLkr5yNlzn/EFRAdgKcHQ7vDPJVDaoD5H3qqiLdAkF0UtG3NHj1X1q2ldGbuutMED4JcJt5c1UsLWb2RNIFDqodv1B26MxL8t3PdnXvcynqCQinAwjKpEH+Z/FPJMumi9Knt6dCQjUfvbzfA8R4GQ3AEZXwIWqTxMe/IxgTuWt3GXHq51rkkjoR7Iz+aBPxzp8Q4oknIR6TzQnpEI=
  - secure: n/nPuPARb4P80rJGTeD7/pblbEZfA1zeO3TtA/2oBAvxLzrEsyhIpg9yw9zEo9speIipum4UVhKI3S45o76JetZo+nyA/POXrrCcWnIL5Gay4Ifs9f8z4fB+tj+IoCg4ZPqSyLpKIbnIUa8H8OKV3oj1WUWvDiD5X9a8pvUvLvAsY3U2MnufPKfZ13OMSrvtxYuPVMLZ+6vwBzyM6IXjD82iP9SgroohT1t3DpdSTM5j6+b+2qYCzu6NrpcK9BAeR3uEfRzkYXxrWyLLWB4XlgqRns/BYwHvGTUyq9D+aXYKdCDdcHXBjQ8AhS8LL2wYpCh4yaHiQwQKBfwRC1516GwAmt4Nc5weFHLX1mlRU0AIHXkDiQ2HRiUuJpRHI8blkDDTEFv33ASVWas3LZwg9wS51PwIb/WbjpJ057uQj35soTsZGZKmQAhlC+mwBgKWEO0D9tp/8Bv//BbBo+WpwH7YlsTSAuJrCW3g+afhvkl9x30QvxnFIcptl4uvJNXip3q1mpn1xmKMvB9e8HGPkctjZGWkvP2VUU6l/5IohvnZxU2reshq7WUs2an+YWVZhxjuKQWYvBBNE5m+NvIeAudAiDgm0UDtD3ChhYlvD8Jfak3ltNSTrArY+Lis9Z9VG1Fgz3jceeJCN+FIiBs6lh2xw+GN7xzmSLBz7LyJapw=
  - secure: pG7u7wmecjRHz9e+oP0crWL4FJBNQEsPBs7q7vVSecF/+PFQVIJrmRMPQnyxYNTBcgCQ5kDl/OaS6zzWxKGXDFTiOOZQBXuRC5AFMV59xMuB0QVqcyZxDtK8ilftdrVOKnvBihcWjWV1ecpE93SVQpD7uaEim8bD9Vxv8yTJ2w4Qunt2wcR9U1AsojOhLgvYrtyQ09Fk6z93BYK5Zgm0+kzCoMniyo+IPqEKb3cmT8kD4zuxwyTHWAvMjpBGYL8OcqV/mKg8wmF3wWZNmQTmYnJUImycFBlyh5f103Ppiuh6USPckZzUlOD8sdkHEo54y+hf/6FKnHSbHaFvibJU3F6j1ETLUX60zefH9k16qkbXulvT+iMGbWn/uRV5Fk1qUfbnIklgBbOwSv6jjHpWWI3H80SEPQqXaL+tpmGtNw/tJqlhXL5qh/JeR3WzCv0MhN+ezmiJxbb37EUZVxWsskuMdQsk39W7Ls7G8gfKtyNSDUijdZsx8O+Cjx0D3vjzBG5XkgPYjqcKJIYE6q6CbskH9obxrlE1TGiu3fvRQOd7sPlCpB9GKHME83GTb2MyXwEfVAeJ3r3BdU71e7LTTYbASx4eIF3nsaQ+P4y5Exn+/zsubYVkwO6c7m9F5fG33KQt/nppb2QqtxKqvWCQrxazA7IIdkh6blQDcjnKWpU=
  - secure: TGqWWjLJmCyZN3imcgSNK/1aAykScY+IsNmnHDsF2nq3WAoD2Umx+KXyRKgWip7Hnz4r/ZZh68L6yJVOXPGVBTVEmHSRNyONPUmQ709ZeFgUzzseWm6W3oQSMp1KCmYXfiVXH4TVNqFWkzaTkPzG7IPJNKAzqOE2zMHnv9JjBLB5c7VfQ8JMnIkGbN40/yk1CqqQaycEBHMqa5V1bWXkPdzT0aq3O15lLZ+Pi2OHEGaoKxRdn830bU2ZTDKj02UBhqPQiSEeie/FTtbY1hkDZ0on4533zad3nWoclUyQ26JdE1vkZuCWR5Yb3JnS9h+F0E5v/7pcTHXJPRaz2MK/vJsNHHGs1E/qbZNOHEam4EFeE2ElHLRHVf8zPrahoX2nvVu2+sCbxl3IqhatgguYpB63QNsgNH4OnzP/fNXUcIElR7S3QEDk9/CvpLmz+uAkP0Vmx6Saa6DTJsPaSC+/WEgoZtcLWswH7NeeP0rQRQblEqRlgRuIcGvrIU4SLXvmRVmif2vCMpgOmt73eBTVCvvru6iuxl9mO46Mf1M7/GPkrha2BAd9O4ufQW3MM6GLH51GxfAkf4U4uF4S3g7zQP4u7xeFFiHsT9mk39x8KoMbrZ2o+wXl/Eua3nZ3LMltpneSwbFD2sNNdSMbzHB32hk12+O7BsB1SCkooesnQKk=
before_install:
- openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv
  -in all.gpg.enc -out all.gpg -d
- gpg --batch --passphrase "${PGP_PASSPHRASE}" --import all.gpg
stages:
- test
- name: publish
  if: "(branch = master) AND (tag IS blank)"
- name: release
  if: "(tag =~ ^[vV][0-9]+\\.[0-9]+\\.[0-9]+(\\-RC[0-9]+)?$ )"
jobs:
  include:
  - stage: test
    script: sbt ++$TRAVIS_SCALA_VERSION +test
  - stage: publish
    script: sbt ++$TRAVIS_SCALA_VERSION +publishSigned
  - stage: release
    script: sbt ++$TRAVIS_SCALA_VERSION -DdistVersion="${TRAVIS_TAG#[vV]}" +publishSigned
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
